code/canvas/base/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index')
]

code/canvas/canvas/urls.py
from asyncio import events
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('base.urls')),
    path('admin/', admin.site.urls),
    path('events/', include('events.urls', namespace='events')),
    path('organization/', include('organization.urls', namespace='organization')),
    path('user/', include('user.urls', namespace='user')),
    path('Admin/', include('Admin.urls', namespace='Admin')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

code/canvas/user/urls.py
from django.urls import path
from . import views
from .views import EventDetail
app_name = 'user'


urlpatterns = [
      path('user_auth/',views.registerlogin , name='user_auth'),  
      path('user_home/',views.user_home , name='user_home'),  
      path('user_profile/',views.user_profile , name='user_profile'),  
      path('user_logout/',views.user_logout , name='user_logout'),
      path('eventdetail/<int:pk>/', EventDetail.as_view(),name= 'event_detail'),   
      path('user_notification/',views.user_notification , name='user_notification'), 
      path('user_cart/<int:pk>/', views.user_cart , name='user_cart'),
      path('user_virtual_box/<int:pk>/',views.user_virtual_box , name='user_virtual_box'),
      path('user_join_form/<int:pk>/',views.user_join_form , name='user_join_form')
        
]

code/canvas/user/models.py
from django.db import models

# Create your models here.

code/canvas/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm

from authentication_user.models import User


class CreateUserForm(UserCreationForm):

    username = forms.CharField(widget=forms.TextInput(attrs={
        "class": "p-2 mt-8 rounded-xl",
        "type": "text",
        "placeholder": "Username"
    }))

    
    email = forms.EmailField(widget=forms.TextInput(attrs={
        "class": "p-2 mt-1 rounded-xl",
        "type": "email",
        "placeholder": "Email"
    }))

    password1 = forms.CharField(widget=forms.TextInput(attrs={
        "class": "p-2 mt-1 rounded-xl",
        "type": "password",
        "placeholder": "Password"
    }))

    password2 = forms.CharField(widget=forms.TextInput(attrs={
        "class": "p-2 mt-1 rounded-xl",
        "type": "password",
        "placeholder": "Confirm Password"
    }))

    

    class Meta:
        model = User
        fields = ['email','username', 'password1', 'password2']

code/canvas/user/views.py
import random
from django.shortcuts import render
from events.models import Event,Images, Genre,Participant
from django.views.generic import ListView, DetailView
# Create your views here.
from django.utils.timezone import now
from .forms import CreateUserForm
from authentication_user.models import User
from django.contrib.auth import login, authenticate ,logout
from django.shortcuts import render,redirect
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.db.models import Count, F

def registerlogin(request):
    # return HttpResponse("Starting the project")
    form = CreateUserForm()
    if request.method == 'POST' and 'registerbtn' in request.POST:
        form = CreateUserForm(request.POST)
        email = request.POST.get('email')
    
        if form.is_valid():
            form.save()
            uobj2 = User.objects.get(email=email)  
            uobj2.isAdmin = False
            uobj2.isUser = True
            uobj2.isOrganization = False
            uobj2.save()

    elif request.method=='POST' and 'loginbtn' in request.POST:
        #email= request.POST.get('email')
        name= request.POST.get('name')
        password = request.POST.get('password')  
        print("done")
        user = authenticate(request, username=name , password = password)
        if (user is not None and user.isUser==True):
                login(request, user)
                print("success")
                return redirect('/user/user_home/')
                
        else:
                # messages.info(request, "Username or Password is incorrect.")
                print("error")

    context = {'form': form }
    return render(request,"user/user_auth.html", context) 

    

@login_required
def user_home(request):
    # return HttpResponse("Starting the project")
   objects= Event.objects.all().order_by('start_date')
   genres = Genre.objects.all()
   participants= Participant.objects.filter(participant_name= request.user.username)
   u_info = User.objects.all()

   print(participants)
   if(participants):
    flag=1
   else:
    flag=0 

#    for obj in objects:
#      today = now().date()
#      obj = Event.objects.filter(start_date__gte=today).order_by('start_date')[:5]

   q= request.POST.get('genre')
   if(q):
    today = now().date()
    objects= Event.objects.filter(genre = q,start_date__gte=today ).order_by('start_date')[:3]
    
   

#    if q =="Photography":
#         today = now().date()
#         objects= Event.objects.filter(genre = q,start_date__gte=today ).order_by('start_date')[:3]
#         print("boop")

#    elif q=="Abstract Art":
#         today = now().date()
#         objects= Event.objects.filter(genre = q, start_date__gte=today ).order_by('start_date')[:3]
#         print("nope")

   context={

        'genres': genres ,
        'objects': objects,
        'participants': participants,
        'flag': flag,
        'u_info': u_info
    }

   

   if request.method == 'POST' and 'paybtn' in request.POST:
    ename=request.POST.get('ename')
    print(ename)

    current_user =request.user.username
    print(current_user)  
    code = random.randint(1000,2000)
    print(code)
    
    participant= Participant.objects.create(participant_name=current_user, event_name= ename, code=code)
    participant.save()


   if request.method == 'POST' and 'pubbtn' in request.POST:
    pub=request.POST.get('pub')
    print(pub)

    current_user =request.user.username
    print(current_user)  
    code = 0
    print(code)
    
    participant= Participant.objects.create(participant_name=current_user, event_name= pub, code=code)
    participant.save()
   
   

   return render(request, 'user/user_home.html',context) 


@login_required
def user_logout(request):  
    logout(request)
    # return HttpResponseRedirect(reverse('/user/user_home/'))
    return render(request, 'user/user_auth.html') 
    


def user_profile(request):  

    current_user = request.user.username
    u_info = User.objects.all()
    if request.method == 'POST' and 'update_pass_btn' in request.POST:
       pass1= request.POST.get('pass1')
       pass2= request.POST.get('pass2')

       u = authenticate(request, username=current_user, password = pass1)
       if (u is not None and u.isUser==True):
           print("vhjfvjehfjj")
           u.password= make_password(pass2)
           u.save()
    
    elif request.method == 'POST' and 'update_img_btn' in request.POST:

        pro_img= request.FILES.get('pro_img')
        u = User.objects.get(username= current_user)
        u.profile_picture = pro_img
        u.save()

    context={
        'u_info' : u_info
    }

    return render(request, 'user/user_profile.html',context) 


def user_notification(request):

    objects= Event.objects.all().order_by('start_date')
    participants= Participant.objects.filter(participant_name= request.user.username)
    u_info = User.objects.all()

    context={
 
        'objects': objects,
        'participants': participants,
        'u_info': u_info
     }
 
    return render(request, 'user/user_notification.html',context) 

    

class EventDetail(DetailView):
    model= Event
    template_name= 'user/event_details.html' 

    # queryset= Event.objects.filter()
    context_object_name= 'event_id'
    
    def get_context_data(self, **kwargs):
        context=super(EventDetail,self).get_context_data(**kwargs)
        context['image']= Images.objects.filter(event_id= self.object)
        return context



def user_cart(request,pk):
    e = Event.objects.filter(event_id= pk)
    print(e[0])
    img= Images.objects.filter(event_id= e[0])
    print(img)
    
    context={
        'e': e[0] ,
        'img':img
    }
    return render(request, 'user/user_cart.html', context)

def user_virtual_box(request,pk):
    e = Event.objects.filter(event_id= pk)
    print(e[0])
    img= Images.objects.filter(event_id= e[0])
    context={
        'e': e[0] ,
        'img':img
    }
    return render(request, 'user/user_virtual_box.html',context)        


def user_join_form(request,pk):
    e = Event.objects.filter(event_id= pk)

    if request.method == "POST":
        name = request.POST.get('name')
        code = request.POST.get('code')
        eid= request.POST.get('eid')
        print(name)
        print(code)
        
        join = Participant.objects.get(participant_name= name, code=code)

        if(join):
            print(join.participant_id)
            print(eid)
            return redirect('user:event_detail', eid)
           



    return render(request, 'user/user_join_form.html', {'e': e[0]})

    

code/canvas/user/templates/user/event_details.html
{% extends 'base.html' %}
{% load static %}

{% block scripts %}

  <script src={% static 'main.js' %} defer> </script>
    <!-- jQuery -->
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js'></script>
    <!-- Gallery JS -->
  <script src={% static 'js/user_gallery_js.js' %} defer> </script>

{% endblock scripts %}

{% block content %}

  <div class="row">
    <div class="col-5">
      <div id="event_name"> <h1>{{event_id.name}} </h1></div>
        <div> {{event_id.name}} will take place:</div>
    </div>
    <div class="col-7">    
       <div id="event-box"> {{event_id.start_date|date:"M d, Y"}}</div>
       <div id="end_date"> {{event_id.end_date|date:"M d, Y"}}</div>

    </div>
  </div>     
     <div> Time left: </div>  
    
     <div id="countdown-box" class="text-center mt-3 h1" width="100" height="128">  
        
     </div>
     <!-- <a href="/user/user_virtual_box/{{event_id.event_id}}" target="_blank">See in Virtual Room</a> -->

     <div class="wrapper" style="display:none" id="virtual">
      <a href="/user/user_virtual_box/{{event_id.event_id}}" target="_blank" class="a1"><span>Virtual Room!</span></a>
    </div>

     <div class="wrapper" style="display:none" id="purchase">
      <a href="/user/user_cart/{{event_id.event_id}}" class="a1"><span>Purchase Art!</span></a>
    </div>

     <br>
     <!-- <a href="/user/user_cart/{{event_id.event_id}}" > Purchase Any Art</a> -->
     
   
            <section style="margin-top:50px">
             
              <div id="img_gallery" style="display:none">
              <div class="gallery">
                {% for image in image %}
                  <div class="gallery-item item-3x4">
                    
                      <img class="thumb placeholder"  src="{{image.image.url}}" data-src="{{image.image.url}}" data-image="{{image.image.url}}" data-title="Sample Photo" alt="Photo by Daniel J. Schwarz">
                      <div class="caption"><span>Click here for display </span></div>
                    </div>
                  
                  {% endfor %}  
              </div>
            </div> 
            <section>
      
    
      {% comment %} </div> {% endcomment %}
      


   
       
{% endblock content %}

code/canvas/user/templates/user/user_cart.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="CodeHim">
    <title>User cart</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <!-- Style CSS -->
    <link rel="stylesheet" href="{% static 'styles/user_cart_style.css' %} ">
	<!-- Demo CSS (No need to include it into your project) -->
	<link rel="stylesheet"  href="{% static 'styles/user_cartdemo_style.css' %} ">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
  
  </head>
  <body>
    <header>
      <a href="#" class="brand">Canvas</a>
      <div class="menu">
        <div class="btn">
          <i class="fas fa-times close-btn"></i>
        </div>
        <a href="/user/user_home" >Home</a>
        <a href="/user/user_profile">Profile</a>
        <a href="/user/user_notification">Notification</a>
        <a href="{% url 'user:user_logout' %}">Logout</a>
      </div>
      <div class="btn">
        <i class="fas fa-bars menu-btn"></i>
      </div>
    </header>



  
<section class="section-main"> 
     <!-- Start DEMO HTML (Use the following code into your project)-->
  <div class="cartbox">
    <div class="cart-modal-overlay">
      <div class="cart-modal">
        <i id="close-btn" class="fas fa-times"></i>
        <h1 class="cart-is-empty">Cart is empty</h1>
      
        <div class="product-rows">
        </div>
        <div class="total">
          <h1 class="cart-total">TOTAL</h1>
            <span class="total-price">$0</span>
              <button class="purchase-btn">PURCHASE</button>
        </div>
      </div>
    </div>
      
<!--   end of cart modal -->
  <div class="cart-btn">
    <i id="cart" class="fas fa-shopping-cart"></i>
      <span class ="cart-quantity">0</span>
  </div>
<!--  products  -->
   

  <div class="items-container">
    {% for img in img %} 
    <div class="card-1 card">
      <img class="product-image" src="{{img.image.url}}" alt="">
        <button class="add-to-cart">Add to cart</button>
          <span class="product-price">{{img.img_price}}</span>
    </div>
    
  {% endfor %} 
   
  </div> 
  
</div> <!--cart-box ends here-->






 </section> 
  
  <script src="{% static 'js/user_cart.js' %}"></script>
  <script type="text/javascript">
    //javascript for navigation bar effect on scroll
    window.addEventListener("scroll", function(){
      var header = document.querySelector("header");
      header.classList.toggle('sticky', window.scrollY > 0);
    });

    //javascript for responsive navigation sidebar menu
    var menu = document.querySelector('.menu');
    var menuBtn = document.querySelector('.menu-btn');
    var closeBtn = document.querySelector('.close-btn');

    menuBtn.addEventListener("click", () => {
      menu.classList.add('active');
    });

    closeBtn.addEventListener("click", () => {
      menu.classList.remove('active');
    });

  </script>
  
    <script type='text/javascript'>var myLink = document.querySelector('a[href="#"]');
      myLink.addEventListener('click', function(e) {
        e.preventDefault();
      });
    </script>
    <script type='text/javascript'>var myLink = document.querySelector('a[href="#"]');
      myLink.addEventListener('click', function(e) {
        e.preventDefault();
      });</script>
    <script type='text/javascript' src='https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js'></script>
    <script type='text/javascript' src='https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js'></script>
  </body>
</html>

code/canvas/user/templates/user/user_home.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User | Home</title>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/user_home_style.css' %} ">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
    <script src=
    "https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js">
        </script>

  
  </head>
  <body>

    <header>
      <a href="#" class="brand">Canvas</a>
      <div class="menu">
        <div class="btn">
          <i class="fas fa-times close-btn"></i>
        </div>
        <a href="/user/user_home" class="active">Home</a>
        <a href="/user/user_profile">Profile</a>
        <a href="/user/user_notification">Notification</a>
        <a href="{% url 'user:user_logout' %}">Logout</a>
      </div>
      <div class="btn">
        <i class="fas fa-bars menu-btn"></i>
      </div>
    </header>


   
      <!-- Filter Events   -->


      
      <section style="background-color:rgb(250, 253, 255); margin-top: 140px;" id="#filter_events">
        <div class = "title-text">
          <br> 
            {% comment %} <h2> Events Coming Up! </h2> {% endcomment %}
        </div>    
      {% if user.is_authenticated%}
         
     {% comment %} <h1> hello {{request.user.username}} </h1>    {% endcomment %}

  
      <div >
        <form action="{% url 'user:user_home' %}" method="post"> {% csrf_token %}
          <label for="genre"class="center_div">Choose a Category to filter:</label>
          <select id="genre" name="genre">
              {% for genre in genres %}
              <option value="{{genre.genre_name}}" name="genre">{{genre.genre_name}}</option>         
              {% endfor %}      
          </select>
          <input type="submit" value="submit" name ="filterbtn">
        </form>
      </div>

    
         
      <div class="container">

        {% for object in objects %} 
        {% if object.is_accepted == True %}
        {% if object.is_not_finished %}
        <div>     
        <div class="filterDiv">
            <div class="card">
              {% for u_info in u_info %}
                            {% if u_info.username == object.org %}
                            {% if u_info.profile_picture %}
                          {% comment %} <img src="{{u_info.profile_picture.url}}" class="request_dp float-left " style="width:80px;height:80px;">  {% endcomment %}
                          <img src="{{u_info.profile_picture.url}}"  style="width:100%">
                          {% endif %}
                             {% endif %}
                          {% endfor %}
                <div class="container2">
                    <div id= "eventName" class="text-dark">
                       <div id="event_name">{{object.name}}</div> 
                       <div id="event_date">Start Date: {{object.start_date|date:"M d, Y"}} </div>
                     
                       <div id="end_date">End Date: {{object.end_date|date:"M d, Y"}}</div>
                       <div id="org">Organization: {{object.org}} </div>
                        <b><p> {{object.genre}}</p></b>

                        {% if object.fee %}

                    

                           <div id ="{{object.event_id}}" ></div>
                                  
                            <div id="x{{object.event_id}}" style="display:block"> <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#{{ object.name }}"> It's a private event,Register NOW!! </button> </div>

                            </div>

                                                          <!-- Modal for event register payment-->
                            <div class="modal fade" id="{{object.name }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                              <div class="modal-dialog">
                                <div class="modal-content">
                                  <div class="modal-header text-dark">
                                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                  </div>
                                  <div class="modal-body text-dark">
                                    You are registering for {{object.name}}
                                  </div>
                                  <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>

                                    <form method="POST" action="/user/user_home/">{% csrf_token %}
                                      
                                    <input type="hidden" name="ename" id="ename" value= "{{object.name}}"> 
                                      <button type="submit" class="btn btn-primary" name="paybtn" id="paybtn" >Pay with Bkash</button>
                                    </form>
                                  </div>
                                </div>
                              </div>
                            </div>


                        {% else %}
                    <form method="POST" action="/user/user_home/">{% csrf_token %}
                      <input type="hidden" name="pub" id="pub" value= "{{object.name}}"> 

                      <div id="z{{object.event_id}}">  </div>
                      <div id="y{{object.event_id}}" style="display:block"> <button type="submit" class="btn btn-primary" name="pubbtn" id="pubbtn">  It is a public event. <br>Click if you are <br> interested!!! </button> </div>

                    </form>     
                        {% endif %}
                        <br>
                        



                        {% if object.start_date_difference %}
                                {% if object.fee %}
                                  <a href="/user/user_join_form/{{object.event_id}}">Event is going on, JOIN NOW!!!</a>

                                  {% else %}
                                  <a href={{object.get_absolute_url3}}>Event is going on, JOIN NOW!!!</a>

                                  {% endif %}
        
                        {% else %}
                             {% if object.fee %}
                              {% comment %} <a href="/user/user_join_form/{{object.event_id}}">Event is going on, JOIN NOW!!!</a> {% endcomment %}
                              <a href={{object.get_absolute_url3}}>Event Details</a>   

                              {% else %}
                      
                              <a href={{object.get_absolute_url3}}>Event Details</a>    
                              
                              {% endif %}
                              
                        {% endif %}
                        
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        {% endif %}
        {% endfor %}        
        {% endif %}
  
      </div>

  </section> 


  {% comment %} <div class="container"> <h1>Notification Tab </h1> 
    
                    <div id="notify">  </div>
                     <br>    
                     
                    </div> {% endcomment %}
  

{% comment %} For filtering {% endcomment %}
<script>
  filterSelection("all")
  function filterSelection(c) {
    var x, i;
    x = document.getElementsByClassName("filterDiv");
    if (c == "all") c = "";
    for (i = 0; i < x.length; i++) {
      w3RemoveClass(x[i], "show");
      if (x[i].className.indexOf(c) > -1) w3AddClass(x[i], "show");
    }
  }
  
  function w3AddClass(element, name) {
    var i, arr1, arr2;
    arr1 = element.className.split(" ");
    arr2 = name.split(" ");
    for (i = 0; i < arr2.length; i++) {
      if (arr1.indexOf(arr2[i]) == -1) {element.className += " " + arr2[i];}
    }
  }
  
  function w3RemoveClass(element, name) {
    var i, arr1, arr2;
    arr1 = element.className.split(" ");
    arr2 = name.split(" ");
    for (i = 0; i < arr2.length; i++) {
      while (arr1.indexOf(arr2[i]) > -1) {
        arr1.splice(arr1.indexOf(arr2[i]), 1);     
      }
    }
    element.className = arr1.join(" ");
  }
  
  // Add active class to the current button (highlight it)
  var btnContainer = document.getElementById("myBtnContainer");
  var btns = btnContainer.getElementsByClassName("btn");
  for (var i = 0; i < btns.length; i++) {
    btns[i].addEventListener("click", function(){
      var current = document.getElementsByClassName("active");
      current[0].className = current[0].className.replace(" active", "");
      this.className += " active";
    });
  }
  </script>




    <script type="text/javascript">
    //javascript for navigation bar effect on scroll
    window.addEventListener("scroll", function(){
      var header = document.querySelector("header");
      header.classList.toggle('sticky', window.scrollY > 0);
    });

    //javascript for responsive navigation sidebar menu
    var menu = document.querySelector('.menu');
    var menuBtn = document.querySelector('.menu-btn');
    var closeBtn = document.querySelector('.close-btn');

    menuBtn.addEventListener("click", () => {
      menu.classList.add('active');
    });

    closeBtn.addEventListener("click", () => {
      menu.classList.remove('active');
    });


    </script>

    <script>
      {% comment %} const dates= [
      {% for participant in  participants %}
      {% for object in objects %}
      {% if participant.event_name == object.name %}
      {
       edate: "{{object.start_date}}",
       etime: "{{object.start_time}}",
       pname: "{{participant.participant_name}}",
       ename: "{{participant.event_name}}"
      },
      {% endif %} 
      {% endfor %}
      {% endfor %}
      ]

      for(let i=0 ; i< dates.length; i++){

        const now= new Date().getTime()
        const edate= Date.parse(dates[i].edate)
        console.log(edate)
        const d= Math.floor((edate / (1000*60*60*24)) - (now /(1000*60*60*24)))
        const h= Math.floor((edate  / (1000*60*60) - (now /(1000*60*60))) %24)
        console.log(d)
        console.log(h)

       
        if(d!=0 && h <= 15){
          
          s = dates[i].pname +"  has shown interest in " + dates[i].ename
          console.log(s)     
          document.getElementById("notify").innerHTML =  s

        }


      } {% endcomment %}

  

     const regbtn = [
     {% for participant in  participants %}
     {% for object in objects %}
     {% if participant.event_name == object.name %}
     {% if object.fee %}
     {
      pname: "{{participant.participant_name}}",
      ename: "{{participant.event_name}}",
      eid : "{{object.event_id}}"
     },
     {% endif %}
     {% endif %} 
     {% endfor %}
     {% endfor %}
     ]

     const obj= [
     {% for object in objects %}
     {% if object.fee %}
     {
      edate: "{{object.start_date}}",
      etime: "{{object.start_time}}",
      eid : "{{object.event_id}}",
      ename: "{{object.name}}"
     },
     {% endif %}
     {% endfor %}
     ]
      
     for(let j=0 ; j< obj.length; j++){
       for(let k=0; k<regbtn.length; k++){
            if(obj[j].ename == regbtn[k].ename){

                    document.getElementById(regbtn[k].eid).innerHTML= "You Have registered for this event"
                    document.getElementById('x'+ regbtn[k].eid).style.display= 'none'
            }
            
        }
     }

     const pub_obj= [
     {% for object in objects %}
     {% if object.fee == null %}
     {
      edate: "{{object.start_date}}",
      etime: "{{object.start_time}}",
      eid : "{{object.event_id}}",
      ename: "{{object.name}}"
     },
     {% endif %}
     {% endfor %}
     ]
    
      
     const pub_btn = [
     {% for participant in  participants %}
     {% for object in objects %}
     {% if participant.event_name == object.name %}
     {% if object.fee == null %}
     {
      pname: "{{participant.participant_name}}",
      ename: "{{participant.event_name}}",
      eid : "{{object.event_id}}"
     },
     {% endif %}
     {% endif %} 
     {% endfor %}
     {% endfor %}
     ]
     
     for(let a=0 ; a< pub_obj.length; a++){
     
      for(let b=0; b<pub_btn.length; b++){
           if(pub_obj[a].ename == pub_btn[b].ename){
                 
                   document.getElementById('z'+pub_btn[b].eid).innerHTML= "You Have registered for this event"
                   document.getElementById('y'+ pub_btn[b].eid).style.display= 'none'
           }
           
       }
    }



     
    </script>  
    
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>    
  </body>
</html>