code/canvas/Admin/urls.py
from django.urls import path
from . import views
from .views import EventDetail

app_name = 'Admin'


urlpatterns = [
      path('Admin_auth/',views.Admin_auth , name='Admin_auth'),  
      path('Admin_home/',views.Admin_home , name='Admin_home'),  
      path('Admin_profile/',views.Admin_profile , name='Admin_profile'),  
      path('Admin_logout/',views.Admin_logout , name='Admin_logout'),  
      path('eventdetail/<int:pk>/', EventDetail.as_view(),name= 'event_detail'),   
      
]

code/canvas/base/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index')
]

code/canvas/canvas/urls.py
from asyncio import events
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('base.urls')),
    path('admin/', admin.site.urls),
    path('events/', include('events.urls', namespace='events')),
    path('organization/', include('organization.urls', namespace='organization')),
    path('user/', include('user.urls', namespace='user')),
    path('Admin/', include('Admin.urls', namespace='Admin')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

code/canvas/organization/urls.py
import imp
from re import A
from django.urls import path
from .views import EventsView,EventDetail
from . import views

app_name= 'organization'

urlpatterns = [
      
      path('organization_auth/',views.registerlogin , name='organization_auth'),
      path('organization_home/',views.organization_home, name='organization_home'),
      path('organization_logout/',views.organization_logout, name='organization_logout'),
      path('organization_profile/',views.organization_profile, name='organization_profile'),
      path('eventform/',views.eventform , name='eventform'),
      # path('eventlist/', EventsView.as_view(), name='event_list'),
      path('eventdetail/<int:pk>/', EventDetail.as_view(),name= 'event_detail'),   
]

code/canvas/user/urls.py
from django.urls import path
from . import views
from .views import EventDetail
app_name = 'user'


urlpatterns = [
      path('user_auth/',views.registerlogin , name='user_auth'),  
      path('user_home/',views.user_home , name='user_home'),  
      path('user_profile/',views.user_profile , name='user_profile'),  
      path('user_logout/',views.user_logout , name='user_logout'),
      path('eventdetail/<int:pk>/', EventDetail.as_view(),name= 'event_detail'),   
      path('user_notification/',views.user_notification , name='user_notification'), 
      path('user_cart/<int:pk>/', views.user_cart , name='user_cart'),
      path('user_virtual_box/<int:pk>/',views.user_virtual_box , name='user_virtual_box'),
      path('user_join_form/<int:pk>/',views.user_join_form , name='user_join_form')
        
]

code/canvas/base/views.py
from multiprocessing import context
from django.shortcuts import render
from events.models import Event,Images, Genre
# Create your views here.
from django.utils.timezone import now


def index(request):
    objects= Event.objects.all()
    genres = Genre.objects.all()
    q= request.POST.get('genre')
    print(q)
    
    # if q=="All":
    today = now().date()
    objects= Event.objects.filter(start_date__gte=today).order_by('start_date')[:5]
    print("blablabla")
    
    if q =="Photography":
      today = now().date()
      objects= Event.objects.filter(genre = q,start_date__gte=today ).order_by('start_date')[:3]
      print("boop")

    elif q=="Abstract Art":
      today = now().date()
      objects= Event.objects.filter(genre = q, start_date__gte=today ).order_by('start_date')[:3]
      print("nope")

    context={

        'genres': genres ,
        'objects': objects
    }
    
    return render(request, 'index.html',context) 

code/canvas/templates/Admin_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

     <!--favicon-->
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico'%}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/file-upload-with-preview/dist/file-upload-with-preview.min.css"/>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/admin_gallery_style.css' %} ">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://unpkg.com/file-upload-with-preview@3.1.3/dist/file-upload-with-preview.min.js"></script>
    
    <!-- custom js -->
    {% block scripts %}
    {% endblock scripts %}

    <title>Admin_Gallery</title>
    <style> {% block css %} {% endblock %}</style>
</head>
<body>
    <header>
        <a href="#" class="brand">Canvas</a>
        <div class="menu">
          <div class="btn">
            <i class="fas fa-times close-btn"></i>
          </div>
          <a href="/Admin/Admin_home">Home</a>
          <a href="/Admin/Admin_profile">Profile</a>
          <a href="{% url 'Admin:Admin_logout' %}">Logout</a>
        </div>
        <div class="btn">
          <i class="fas fa-bars menu-btn"></i>
        </div>
      </header>

    <section class="countdown" style = "padding-top: 100px;" >
      <div class="container mt-3">

       {% block content %}
       
       {% endblock content %}
    </div>
    {% block js %} {% endblock%} 
</section>

                
              </div>
          </div>
          </div>
      </section>
  
  
  
    <script type="text/javascript">

      {% comment %} rating {% endcomment %}
    $(':radio').change(function() {
        console.log('New star rating: ' + this.value);
    });

      {% comment %} rating ends {% endcomment %}


      //javascript for navigation bar effect on scroll
      window.addEventListener("scroll", function(){
        var header = document.querySelector("header");
        header.classList.toggle('sticky', window.scrollY > 0);
      });
  
      //javascript for responsive navigation sidebar menu
      var menu = document.querySelector('.menu');
      var menuBtn = document.querySelector('.menu-btn');
      var closeBtn = document.querySelector('.close-btn');
  
      menuBtn.addEventListener("click", () => {
        menu.classList.add('active');
      });
  
      closeBtn.addEventListener("click", () => {
        menu.classList.remove('active');
      });
    </script>
</body>
</html>

code/canvas/templates/Org_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

     <!--favicon-->
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico'%}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/file-upload-with-preview/dist/file-upload-with-preview.min.css"/>
     <link rel="stylesheet" type="text/css" href="{% static 'styles/organization_gallery_style.css' %} "> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://unpkg.com/file-upload-with-preview@3.1.3/dist/file-upload-with-preview.min.js"></script>
    
    <!-- custom js -->
    {% block scripts %}
    {% endblock scripts %}

    <title>Organization</title>
    <style> {% block css %} {% endblock %}</style>
</head>
<body>
    <header>
        <a href="#" class="brand">Canvas</a>
        <div class="menu">
          <div class="btn">
            <i class="fas fa-times close-btn"></i>
          </div>
          <a href="/organization/organization_home">Home</a>
          <a href="/organization/organization_profile">Profile</a>
          <a href="/organization/organization_profile">Event</a>
          <a href="{% url 'organization:organization_logout' %}">Logout</a>
        </div>
        <div class="btn">
          <i class="fas fa-bars menu-btn"></i>
        </div>
      </header>

    <section class="countdown" style = "padding-top: 100px;" >
      <div class="container mt-3">

       {% block content %}
       
       {% endblock content %}
    </div>
    {% block js %} {% endblock%} 
</section>

    
                
              </div>
          </div>
          </div>
      </section>
  
     
  
  
    <script type="text/javascript">

      {% comment %} rating {% endcomment %}
    $(':radio').change(function() {
        console.log('New star rating: ' + this.value);
    });

      {% comment %} rating ends {% endcomment %}


      //javascript for navigation bar effect on scroll
      window.addEventListener("scroll", function(){
        var header = document.querySelector("header");
        header.classList.toggle('sticky', window.scrollY > 0);
      });
  
      //javascript for responsive navigation sidebar menu
      var menu = document.querySelector('.menu');
      var menuBtn = document.querySelector('.menu-btn');
      var closeBtn = document.querySelector('.close-btn');
  
      menuBtn.addEventListener("click", () => {
        menu.classList.add('active');
      });
  
      closeBtn.addEventListener("click", () => {
        menu.classList.remove('active');
      });
    </script>
    <script type='text/javascript' src='https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js'></script>
    <script type='text/javascript' src='https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js'></script>
  </body>
</html>

code/canvas/templates/auth.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Authentication</title>
        <meta charset="UTF-8">
        <meta name="viewport" consent="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="{% static 'styles/auth_style.css' %} ">
        
        <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@400;600;700;800&display=swap" rel="stylesheet">
    </head>

    <body>
        <div class="cont">
            <div class="form Sign-in">
                <h2>Sign In</h2>
                <label>
                    <span>Email Address</span>
                    <input type="email" name="email">
                </label>
                <label>
                    <span>Password</span>
                    <input type="password" name="password">
                </label>
                <button class="submit" type="button">Sign In</button>
                <p class="forget-pass">Forget Password ?</p>

                <div class="social-media">
                    <ul>
                        <li><img src="{% static 'images/facebook.png' %}" class="facebook"></li>
                        <li><img src="{% static 'images/twitter.png' %}" class="twitter"></li>
                        <li><img src="{% static 'images/linkedin.png' %}" class="linkedin"></li>
                        <li><img src="{% static 'images/instagram.png' %}" class="instagram"></li>
                    </ul>
                </div>
            </div>

            
            <div class="sub-cont">
                <div class="img">
                    <div class="img-text m-up"> 
                    <h2>New here?</h2>
                    <p>Sign up and explore through the world of arts!</p>
                </div>
                    <div class="img-text m-in"> 
                    <h2>One of us?</h2>
                    <p>If you already have an account, just sign in.We have missed you!</p>
                </div>
                <div class="img-btn">
                    <span class="m-up">Sign Up</span>
                    <span class="m-in">Sign In</span>
                </div>           
            </div>
            <div class="form Sign-up">
                <h2>Sign up</h2>
                <label>
                    <span>Name</span>
                    <input type="text">
                </label>
                <label>
                    <span>Email</span>
                    <input type="email">
                </label>
                <label>
                    <span>Password</span>
                    <input type="password">
                </label>
                <label>
                    <span>Confirm Password</span>
                    <input type="password">
                </label>
                <button type="button" class="submit">Sign Up Now</button>
            </div>
        </div>
     </div>
    <script type="text/javascript" src="{% static 'styles/script.js' %}"></script>
  </body>
</html>

code/canvas/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

     <!--favicon-->
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico'%}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/file-upload-with-preview/dist/file-upload-with-preview.min.css"/>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/user_gallery_style.css' %} ">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://unpkg.com/file-upload-with-preview@3.1.3/dist/file-upload-with-preview.min.js"></script>
    
    <!-- custom js -->
    {% block scripts %}
    {% endblock scripts %}

    <title>User_Gallery</title>
    <style> {% block css %} {% endblock %}</style>
</head>
<body>
    <header>
        <a href="#" class="brand">Canvas</a>
        <div class="menu">
          <div class="btn">
            <i class="fas fa-times close-btn"></i>
          </div>
          <a href="/user/user_home">Home</a>
          <a href="/user/user_profile">Profile</a>
          <a href="/user/user_notification">Notification</a>
          <a href="{% url 'user:user_logout' %}">Logout</a>
        </div>
        <div class="btn">
          <i class="fas fa-bars menu-btn"></i>
        </div>
      </header>

    <section class="countdown" style = "padding-top: 100px;" >
      <div class="container mt-3">

       {% block content %}
       
       {% endblock content %}
    </div>
    {% block js %} {% endblock%} 
</section>

    {% comment %} <section class="section-main">

        <div class="rt-container">
          <div class="col-rt-12">
              <div class="Scriptcontent">
                <h2>Gallery</h2>
        <section>
          <!-- Photos by Daniel J. Schwarz (unsplash.com/@danieljschwarz) -->
          <div class="gallery">
              <div class="gallery-item item-3x4">
                  <img class="thumb placeholder" src="{% static 'images\1.jpg' %}" data-src="{% static 'images\1.jpg' %}" data-image="{% static 'images\1.jpg' %}" data-title="Sample Photo" alt="Photo by Daniel J. Schwarz">
                  <div class="caption"><span>Caption </span></div>
              </div>
              <div class="gallery-item item-3x4">
                  <img class="thumb placeholder" src="{% static 'images\2.jpg' %}" data-src="{% static 'images\2.jpg' %}" data-image="{% static 'images\2.jpg' %}" data-title="Sample Photo" alt="Photo by Daniel J. Schwarz">
                  <div class="caption"><span>Caption </span></div>
              </div>
              <div class="gallery-item item-3x4">
                  <img class="thumb placeholder" src="{% static 'images\3.jpg' %}" data-src="{% static 'images\3.jpg' %}" data-image="{% static 'images\3.jpg' %}" data-title="Sample Photo" alt="Photo by Daniel J. Schwarz">
                  <div class="caption"><span>Caption </span></div>
              </div>
              <div class="gallery-item item-3x4">
                  <img class="thumb placeholder" src="{% static 'images\4.jpg' %}" data-src="{% static 'images\4.jpg' %}" data-image="{% static 'images\4.jpg' %}" data-title="Sample Photo" alt="Photo by Daniel J. Schwarz">
                  <div class="caption"><span>Caption </span></div>
              </div>
              <div class="gallery-item item-3x4">
                  <img class="thumb placeholder" src="{% static 'images\5.jpg' %}" data-src="{% static 'images\5.jpg' %}" data-image="{% static 'images\5.jpg' %}" data-title="Sample Photo" alt="Photo by Daniel J. Schwarz">
                  <div class="caption"><span>Caption </span></div>
              </div>
              <div class="gallery-item item-3x4">
                  <img class="thumb placeholder" src="{% static 'images\6.jpg' %}" data-src="{% static 'images\6.jpg' %}" data-image="{% static 'images\6.jpg' %}" data-title="Sample Photo" alt="Photo by Daniel J. Schwarz">
                  <div class="caption"><span>Caption </span></div>
              </div>
            
             
          </div>
        </section>

        {% comment %} Rating {% endcomment %}

        {% comment %} <form class="rating">
          <label>
            <input type="radio" name="stars" value="1" />
            <span class="icon">★</span>
          </label>
          <label>
            <input type="radio" name="stars" value="2" />
            <span class="icon">★</span>
            <span class="icon">★</span>
          </label>
          <label>
            <input type="radio" name="stars" value="3" />
            <span class="icon">★</span>
            <span class="icon">★</span>
            <span class="icon">★</span>   
          </label>
          <label>
            <input type="radio" name="stars" value="4" />
            <span class="icon">★</span>
            <span class="icon">★</span>
            <span class="icon">★</span>
            <span class="icon">★</span>
          </label>
          <label>
            <input type="radio" name="stars" value="5" />
            <span class="icon">★</span>
            <span class="icon">★</span>
            <span class="icon">★</span>
            <span class="icon">★</span>
            <span class="icon">★</span>
          </label>
        </form> {% endcomment %}

        {% comment %} Rating {% endcomment %}
                
              </div>
          </div>
          </div>
      </section>
  
      {% comment %} Setion ends {% endcomment %}
  
  
    <script type="text/javascript">

      {% comment %} rating {% endcomment %}
    $(':radio').change(function() {
        console.log('New star rating: ' + this.value);
    });

      {% comment %} rating ends {% endcomment %}


      //javascript for navigation bar effect on scroll
      window.addEventListener("scroll", function(){
        var header = document.querySelector("header");
        header.classList.toggle('sticky', window.scrollY > 0);
      });
  
      //javascript for responsive navigation sidebar menu
      var menu = document.querySelector('.menu');
      var menuBtn = document.querySelector('.menu-btn');
      var closeBtn = document.querySelector('.close-btn');
  
      menuBtn.addEventListener("click", () => {
        menu.classList.add('active');
      });
  
      closeBtn.addEventListener("click", () => {
        menu.classList.remove('active');
      });
      {% comment %} </script>
  
          <!-- jQuery -->
          <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js'></script>
          <!-- Gallery JS -->
          <script src="{% static 'js/user_gallery_js.js' %}"></script>  {% endcomment %}
   

</body>
</html>